AllCops:
  Exclude:
     - 'vendor/**/*'
     - 'test/fixtures/**/*'
     - 'tmp/**/*'
##################### Metrics ##################################

Metrics/LineLength:
  Max: 130

Metrics/ClassLength:
  CountComments: false
  Max: 150

Metrics/LineLength:
  Max: 150
  Exclude:
    - 'test/test_data.rb'

##################### Style ##################################

# Use nested module/class definitions instead of compact style.
# NG: module Gem::Search
Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'gmail.gemspec'
    - 'test/**/*'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30
